"""Browse-session cookie handoff (sanctioned internal path).

Reads a saved `agent-do browse` session's storageState JSON and emits a
temporary Netscape cookies.txt for yt-dlp consumption. Strict rules:

  - Never print or log cookie values.
  - Temp file is 0600 and lives in a 0700 temp directory.
  - Caller is responsible for trap/finally cleanup (see safe_cookie_file).
  - Only operates on named sessions saved by agent-browse.
"""

from __future__ import annotations

import json
import os
import stat
import tempfile
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator, Optional

SESSIONS_ROOT = Path.home() / ".agent-browse" / "sessions"


def list_sessions() -> list[dict]:
    """Return [{name, domains[], cookie_count, last_modified}] for saved sessions.
    Cookie values never appear in the result.
    """
    if not SESSIONS_ROOT.exists():
        return []

    results = []
    for entry in sorted(SESSIONS_ROOT.iterdir()):
        storage = entry / "storage.json"
        if not entry.is_dir() or not storage.exists():
            continue
        try:
            data = json.loads(storage.read_text())
        except (OSError, json.JSONDecodeError):
            continue

        cookies = data.get("cookies") or []
        domains = sorted({_normalize_domain(c.get("domain", "")) for c in cookies if c.get("domain")})
        results.append({
            "name": entry.name,
            "domains": [d for d in domains if d],
            "cookie_count": len(cookies),
            "last_modified": int(storage.stat().st_mtime),
        })
    return results


def session_path(name: str) -> Optional[Path]:
    candidate = SESSIONS_ROOT / name / "storage.json"
    return candidate if candidate.exists() else None


def _normalize_domain(domain: str) -> str:
    return domain.lstrip(".") if domain else ""


def _format_cookie_line(cookie: dict) -> Optional[str]:
    name = cookie.get("name")
    value = cookie.get("value")
    domain = cookie.get("domain", "")
    if not name or value is None or not domain:
        return None

    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    path = cookie.get("path", "/") or "/"
    secure = "TRUE" if cookie.get("secure") else "FALSE"
    expires = cookie.get("expires", -1)
    try:
        expires_int = int(expires) if expires and expires > 0 else 0
    except (TypeError, ValueError):
        expires_int = 0

    return "\t".join([domain, include_subdomains, path, secure, str(expires_int), name, value])


@contextmanager
def safe_cookie_file(session_name: str) -> Iterator[Path]:
    """Yield a path to a temporary Netscape cookies.txt derived from the named
    browse session. The file (and its parent dir) are removed on exit even if
    the caller raises.

    Raises FileNotFoundError if the session does not exist.
    Raises ValueError if the storage state contains no usable cookies.
    """
    storage_path = session_path(session_name)
    if storage_path is None:
        raise FileNotFoundError(f"browse session not found: {session_name}")

    data = json.loads(storage_path.read_text())
    cookies = data.get("cookies") or []
    lines = [_format_cookie_line(c) for c in cookies]
    lines = [l for l in lines if l is not None]
    if not lines:
        raise ValueError(f"browse session {session_name!r} has no usable cookies")

    tmpdir = Path(tempfile.mkdtemp(prefix="agent-transcribe-cookies-"))
    os.chmod(tmpdir, stat.S_IRWXU)
    cookies_file = tmpdir / "cookies.txt"

    fd = os.open(str(cookies_file), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write("# Netscape HTTP Cookie File\n")
            fh.write("# generated by agent-transcribe; ephemeral; do not redistribute\n")
            for line in lines:
                fh.write(line)
                fh.write("\n")
    except Exception:
        try:
            cookies_file.unlink(missing_ok=True)
            tmpdir.rmdir()
        except OSError:
            pass
        raise

    try:
        yield cookies_file
    finally:
        try:
            cookies_file.unlink(missing_ok=True)
        except OSError:
            pass
        try:
            tmpdir.rmdir()
        except OSError:
            pass


def cookie_summary(session_name: str) -> dict:
    """Return non-sensitive summary of a session's cookies (count + domains)."""
    storage_path = session_path(session_name)
    if storage_path is None:
        return {"exists": False}
    data = json.loads(storage_path.read_text())
    cookies = data.get("cookies") or []
    domains = sorted({_normalize_domain(c.get("domain", "")) for c in cookies if c.get("domain")})
    return {
        "exists": True,
        "name": session_name,
        "cookie_count": len(cookies),
        "domains": [d for d in domains if d],
    }
